server.port=${TRADING_SERVICE_PORT:18092}
spring.threads.virtual.enabled=true

people.service.url=${PEOPLE_SERVICE_URL:http://${PEOPLE_SERVICE_HOST:localhost}:18089}
validation.service.url=${VALIDATION_SERVICE_URL:http://${VALIDATION_SERVICE_HOST:localhost}:18094}

trade.feed.address=${TRADE_FEED_ADDRESS:http://${TRADE_FEED_HOST:localhost}:18086}

# To avoid "Request header is too large" when application is backed by oidc proxy.
server.max-http-request-header-size=1000000

logging.level.root=info
