server.port=${VALIDATION_SERVICE_PORT:18094}
spring.threads.virtual.enabled=true

reference.data.service.url=${REFERENCE_DATA_SERVICE_URL:http://${REFERENCE_DATA_HOST:localhost}:18085}
account.service.url=${ACCOUNT_SERVICE_URL:http://${ACCOUNT_SERVICE_HOST:localhost}:18088}

logging.level.root=info
