#!/usr/bin/env bash
# Reset the estate for a clean AE run:
#   1. wipe the workspace (git clones the demos mutate) and re-seed it
#   2. wipe demo/out (generated artifacts) — leave-behinds under demo/reports are regenerated by the demos
#   3. re-install core-dates 1.4.0/1.4.1/1.5.0 into ~/.m2 (FS_RESEED_CORE_DATES=1 forces a rebuild)
#   4. kill any client-portal left listening from Demo 3
# Sources: $ESTATE/repos/ when present, else the mapped COG-GTM repos (scripts/repo-map.tsv) cloned into $FS_SOURCES.
# Idempotent. Takes ~1 min (~3 min with FS_RESEED_CORE_DATES=1).
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$HERE/lib.sh"
ESTATE="$(cd "$HERE/.." && pwd)"
WS="${FS_WORKSPACE:-$HOME/finserv-workspace}"

pkill -f "client-portal/src/server.js" 2>/dev/null || true
pkill -f "finserv-workspace/client-portal" 2>/dev/null || true

log "clearing generated artifacts"
rm -rf "$ESTATE/demo/out"
mkdir -p "$ESTATE/demo/out"

if [[ ! -d "$ESTATE/repos" || "${FS_SOURCE_MODE:-}" == "remote" ]]; then
  log "remote-source mode: syncing COG-GTM repos per scripts/repo-map.tsv into $FS_SOURCES"
  sources_sync
fi

log "re-seeding workspace at $WS"
for r in $(repo_list); do
  [[ "$r" == core-dates && "${FS_RESEED_CORE_DATES:-0}" != "1" ]] && continue
  rm -rf "$WS/$r"
done
"$HERE/seed-workspace.sh"

for v in 1.4.0 1.4.1 1.5.0; do
  [[ -f "$HOME/.m2/repository/com/ardencm/posttrade/core-dates/$v/core-dates-$v.jar" ]] \
    || { warn "core-dates $v missing from ~/.m2 — rebuilding releases"; FS_RESEED_CORE_DATES=1 "$HERE/seed-core-dates-releases.sh"; break; }
done
[[ -f "$HOME/.m2/repository/com/ardencm/platform/common-java-bom/2026.3.0/common-java-bom-2026.3.0.pom" ]] \
  || (cd "$(source_dir common-java-bom)" && mvn -q install)

# Demo 1 remediation targets that must be resolvable offline (the estate's Artifactory URL is a fixture).
[[ -f "$HOME/.m2/repository/org/apache/commons/commons-compress/1.26.0/commons-compress-1.26.0.jar" ]] \
  || mvn -q dependency:get -Dartifact=org.apache.commons:commons-compress:1.26.0
if ! command -v terraform >/dev/null && [[ ! -x "$HOME/.local/bin/terraform" ]]; then
  log "installing terraform 1.9.8 to ~/.local/bin (platform-terraform fmt check)"
  mkdir -p "$HOME/.local/bin"
  curl -sSfL -o /tmp/tf.zip https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip \
    && unzip -o -q /tmp/tf.zip -d "$HOME/.local/bin" || warn "terraform install failed; platform-terraform findings will report 'blocked'"
fi
python3 -c "import pytest, yaml" 2>/dev/null || pip install -q pytest PyYAML

log "reset complete"
